import type { BrainAdminServiceConfig } from "./admin-service.js";

function escapeHtml(value: string): string {
  return value.replace(/[&<>"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char] ?? char);
}

export function renderBrainAdminPage(config: BrainAdminServiceConfig): string {
  const payload = JSON.stringify({ apiBase: "/api/admin/brain", routePath: config.routePath });
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Brain Control Plane</title><style>
  body{margin:0;font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif;background:#0f172a;color:#e5e7eb}main{max-width:1200px;margin:0 auto;padding:32px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}.card{background:#111827;border:1px solid #334155;border-radius:16px;padding:20px;box-shadow:0 12px 30px #0004}h1,h2,h3{margin:0 0 12px}.muted{color:#94a3b8}.bad{color:#f87171}.ok{color:#86efac}input,select,button,textarea{box-sizing:border-box;font:inherit;border-radius:10px;border:1px solid #475569;background:#020617;color:#e5e7eb;padding:10px}input,textarea,select{width:100%}button{cursor:pointer;background:#2563eb;border-color:#3b82f6;width:auto}button.secondary{background:#1f2937}label{display:block;margin:10px 0 4px}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;white-space:pre-wrap}.manifest{min-height:360px}.hidden{display:none}</style></head><body><main>
  <h1>Brain Control Plane</h1><p class="muted">Clerk-protected admin service for Brain as the user-facing app surface. codex-chat remains the internal engine for Slack signature verification, runtime normalization, and message handling.</p>
  <section id="status" class="card"><h2>Loading…</h2><p class="muted">Checking server-side admin allowlist.</p></section>
  <div class="grid">
    <section class="card"><h2>Health</h2><pre id="health" class="mono"></pre><button onclick="refresh()">Refresh</button></section>
    <section class="card"><h2>Settings</h2><pre id="settings" class="mono"></pre></section>
    <section class="card"><h2>Slack settings</h2><p class="muted">Explicit write-only controls for codex-chat Slack env. Responses show presence only. Public Events URL is <span class="mono">https://brain.decisive-outcomes.com/api/slack/events</span>.</p><div id="slack-fields"></div><label>Approval</label><input id="slack-approval" placeholder="write Slack settings"><button onclick="writeSlackSettings()">Write Slack settings</button><pre id="slack-result" class="mono"></pre></section>
    <section class="card"><h2>Slack manifest</h2><p class="muted">Rendered by codex-chat's checked-in manifest script so Brain does not fork Slack app semantics.</p><div class="row"><button onclick="loadManifest()">Render</button><button class="secondary" onclick="copyManifest()">Copy</button><button class="secondary" onclick="downloadManifest()">Download</button></div><p id="manifest-url" class="mono"></p><textarea id="manifest-text" class="mono manifest" readonly></textarea><pre id="manifest-result" class="mono"></pre></section>
    <section class="card"><h2>Write codex-chat env/config</h2><p class="muted">Generic escape hatch. Prefer Slack settings above for Slack keys. Values are write-only; responses show presence only.</p><label>Key</label><input id="env-key" placeholder="CODEX_CHAT_BASE_URL"><label>Value</label><input id="env-value" type="password" placeholder="write-only"><label>Approval</label><input id="env-approval" placeholder="write env"><button onclick="writeEnv()">Write entry</button><pre id="env-result" class="mono"></pre></section>
    <section class="card"><h2>Deploy / restart</h2><p class="muted">Operations require exact approval text and are audited.</p><label>Operation</label><select id="op"><option>plan</option><option>restart</option><option>deploy</option></select><label>Approval</label><input id="op-approval" placeholder="plan codex-chat.service"><button onclick="runOperation()">Run</button><pre id="op-result" class="mono"></pre></section>
  </div>
</main><script type="application/json" id="brain-admin-config">${escapeHtml(payload)}</script><script>
const SLACK_KEYS=['CODEX_CHAT_SLACK_ENABLED','CODEX_CHAT_BASE_URL','CODEX_CHAT_SLACK_EVENTS_PATH','SLACK_SIGNING_SECRET','SLACK_BOT_TOKEN','SLACK_APP_TOKEN'];
const CONFIG=JSON.parse(document.getElementById('brain-admin-config').textContent);
let lastManifestText='';
async function tokenHeaders(){if(window.Clerk&&Clerk.session&&Clerk.session.getToken){try{return {authorization:'Bearer '+await Clerk.session.getToken()}}catch{}}return {}}
async function api(path,options={}){const headers={...(await tokenHeaders()),...(options.headers||{})};if(options.body)headers['content-type']='application/json';const res=await fetch(CONFIG.apiBase+path,{...options,headers});const text=await res.text();let body;try{body=JSON.parse(text)}catch{body={raw:text}}if(!res.ok)throw Object.assign(new Error(body.error||res.statusText),{status:res.status,payload:body});return body}
function show(id,value){document.getElementById(id).textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
function renderSlackFields(settings){const present=new Map((settings?.env?.keys||[]).map(k=>[k.key,k.present]));document.getElementById('slack-fields').innerHTML=SLACK_KEYS.map(k=>'<label>'+k+' <span class="muted">'+(present.get(k)?'present':'not set')+'</span></label><input id="slack-'+k+'" type="password" placeholder="leave blank to keep existing value">').join('')}
async function refresh(){try{const me=await api('/me');document.getElementById('status').innerHTML='<h2 class="ok">Signed in</h2><p class="muted">'+(me.email||'allowlisted admin')+'</p>';show('health',await api('/health'));const settings=await api('/settings');show('settings',settings);renderSlackFields(settings.slack||await api('/slack/settings'))}catch(e){document.getElementById('status').innerHTML='<h2 class="bad">Denied</h2><p>'+(e.payload?.error||e.message)+'</p>'}}
async function writeEnv(){try{show('env-result',await api('/codex-chat/env',{method:'POST',body:JSON.stringify({entries:{[document.getElementById('env-key').value]:document.getElementById('env-value').value},approval:document.getElementById('env-approval').value})}));document.getElementById('env-value').value='';await refresh()}catch(e){show('env-result',e.payload||e.message)}}
async function writeSlackSettings(){try{const entries={};for(const k of SLACK_KEYS){const v=document.getElementById('slack-'+k).value;if(v)entries[k]=v}show('slack-result',await api('/slack/settings',{method:'POST',body:JSON.stringify({entries,approval:document.getElementById('slack-approval').value})}));for(const k of SLACK_KEYS)document.getElementById('slack-'+k).value='';await refresh()}catch(e){show('slack-result',e.payload||e.message)}}
async function loadManifest(){try{const m=await api('/slack/manifest');lastManifestText=m.text||JSON.stringify(m.manifest,null,2)+'\\n';document.getElementById('manifest-text').value=lastManifestText;document.getElementById('manifest-url').textContent='request_url: '+m.requestUrl;show('manifest-result',{renderer:m.renderer,eventsPath:m.eventsPath})}catch(e){show('manifest-result',e.payload||e.message)}}
async function copyManifest(){if(!lastManifestText)await loadManifest();await navigator.clipboard.writeText(lastManifestText);show('manifest-result','Copied manifest JSON to clipboard.')}
async function downloadManifest(){if(!lastManifestText)await loadManifest();const blob=new Blob([lastManifestText],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='codex-chat.slack.manifest.json';a.click();URL.revokeObjectURL(url)}
async function runOperation(){try{show('op-result',await api('/codex-chat/operation',{method:'POST',body:JSON.stringify({operation:document.getElementById('op').value,approval:document.getElementById('op-approval').value})}));await refresh()}catch(e){show('op-result',e.payload||e.message)}}refresh();</script></body></html>`;
}

export function renderBrainAdminSignInPage(config: BrainAdminServiceConfig, redirectUrl: string): string {
  const payload = JSON.stringify({ publishableKey: config.clerkPublishableKey, redirectUrl });
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in to Brain Control Plane</title><style>body{font:16px system-ui;margin:3rem;max-width:720px;background:#0f172a;color:#e5e7eb}.card{border:1px solid #334155;border-radius:16px;padding:24px;background:#111827}.bad{color:#f87171}</style></head><body><section class="card"><h1>Sign in to Brain Control Plane</h1><p>Use an allowlisted Clerk account.</p><div id="sign-in"></div><p id="error" class="bad"></p></section><script type="application/json" id="config">${escapeHtml(payload)}</script><script async crossorigin="anonymous" data-clerk-publishable-key="${escapeHtml(config.clerkPublishableKey)}" src="https://cdn.jsdelivr.net/npm/@clerk/clerk-js@latest/dist/clerk.browser.js"></script><script>const c=JSON.parse(document.getElementById('config').textContent);async function mount(){for(let i=0;i<80&&!window.Clerk;i++)await new Promise(r=>setTimeout(r,100));if(!window.Clerk){document.getElementById('error').textContent='Clerk did not load.';return}await Clerk.load();if(Clerk.user){location.assign(c.redirectUrl);return}Clerk.mountSignIn(document.getElementById('sign-in'),{forceRedirectUrl:c.redirectUrl,fallbackRedirectUrl:c.redirectUrl});}mount().catch(e=>document.getElementById('error').textContent=e.message||String(e));</script></body></html>`;
}

export function renderBrainAdminDeniedPage(error: string, signInUrl: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Brain Control Plane denied</title><style>body{font:16px system-ui;margin:3rem;max-width:720px;background:#0f172a;color:#e5e7eb}.card{border:1px solid #334155;border-radius:16px;padding:24px;background:#111827}.bad{color:#f87171}a{color:#38bdf8}</style></head><body><section class="card"><h1>Brain Control Plane access denied</h1><p class="bad">${escapeHtml(error)}</p><p>Admin routes require Clerk auth and a non-empty server-side allowlist.</p><p><a href="${escapeHtml(signInUrl)}">Sign in or switch Clerk account</a></p></section></body></html>`;
}
