export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonRecord = Record<string, JsonValue>;

export type ChannelKind = "telegram" | "web" | "ios" | "cli" | "loop" | "monitor" | "system" | (string & {});

export type InboundEventKind =
  | "message"
  | "command"
  | "attachment"
  | "callback"
  | "lifecycle"
  | "delivery";

export interface EntryPointCapabilities {
  replies?: boolean;
  edits?: boolean;
  artifactUploads?: boolean;
  statusUpdates?: boolean;
  reactions?: boolean;
  attachments?: boolean;
  commands?: boolean;
  [capability: string]: boolean | undefined;
}

export interface EntryPointRef {
  entrypointId: string;
  channelKind: ChannelKind;
  displayName?: string;
  capabilities?: EntryPointCapabilities;
}

export interface ExternalConversationRef {
  id?: string;
  threadId?: string;
  label?: string;
  url?: string;
  metadata?: JsonRecord;
}

export interface ExternalActorRef {
  id?: string;
  username?: string;
  displayName?: string;
  role?: "user" | "admin" | "system" | "service" | (string & {});
  metadata?: JsonRecord;
}

export interface BrainAttachment {
  id?: string;
  kind: "image" | "document" | "voice" | "audio" | "video" | "unknown" | (string & {});
  localPath?: string;
  uri?: string;
  mimeType?: string;
  originalName?: string;
  sizeBytes?: number;
  sha256?: string;
  metadata?: JsonRecord;
}

export interface ReplyContext {
  externalMessageId?: string;
  snippet?: string;
  contentType?: string;
  actor?: ExternalActorRef;
  metadata?: JsonRecord;
}

export interface EntryPointInboundEvent {
  /** Stable event id generated by the adapter/runtime boundary. */
  id: string;
  kind: InboundEventKind;
  workspaceId: string;
  entrypoint: EntryPointRef;
  /** Plain text normalized for provider prompts. */
  text?: string;
  /** Slash-command or adapter command name without channel-specific syntax. */
  command?: string;
  args?: string[];
  attachments?: BrainAttachment[];
  actor?: ExternalActorRef;
  conversation?: ExternalConversationRef;
  reply?: ReplyContext;
  correlationId?: string;
  receivedAt: string;
  metadata?: JsonRecord;
}

export type OutboundRoute = "originating-entrypoint" | "explicit-entrypoint" | "admins" | "store-only" | "silent";

export interface OutboundTarget {
  route?: OutboundRoute;
  entrypointId?: string;
  conversationId?: string;
  threadId?: string;
  replyToExternalMessageId?: string;
}

export interface BaseOutboundAction {
  id?: string;
  idempotencyKey?: string;
  originatingEventId?: string;
  workspaceId?: string;
  target?: OutboundTarget;
  createdAt?: string;
  metadata?: JsonRecord;
}

export interface SendTextAction extends BaseOutboundAction {
  type: "send_text";
  text: string;
  format?: "text" | "markdown" | "markdownv2";
}

export interface SendArtifactAction extends BaseOutboundAction {
  type: "send_artifact";
  path?: string;
  uri?: string;
  caption?: string;
  asDocument?: boolean;
  deleteAfterSend?: boolean;
  mimeType?: string;
}

export interface ShowStatusAction extends BaseOutboundAction {
  type: "show_status";
  status: "typing" | "running" | "done" | "failed" | "cancelled" | (string & {});
  text?: string;
}

export interface RequestClarificationAction extends BaseOutboundAction {
  type: "request_clarification";
  text: string;
  choices?: string[];
}

export interface ReactAction extends BaseOutboundAction {
  type: "react";
  emoji: string;
}

export interface EditMessageAction extends BaseOutboundAction {
  type: "edit_message";
  text: string;
  externalMessageId?: string;
  format?: "text" | "markdown" | "markdownv2";
}

export interface DispatchSubagentAction extends BaseOutboundAction {
  type: "dispatch_subagent";
  profile: string;
  prompt: string;
  summary: string;
  route?: "return_to_main" | "send_to_user" | "send_progress_and_return" | "send_to_admins" | "store_only" | "silent";
  timeoutSec?: number;
  model?: string;
  effort?: "none" | "minimal" | "low" | "medium" | "high" | "xhigh";
  images?: string[];
}

export interface EnqueueMainAction extends BaseOutboundAction {
  type: "enqueue_main";
  text: string;
}

export type BrainOutboundAction =
  | SendTextAction
  | SendArtifactAction
  | ShowStatusAction
  | RequestClarificationAction
  | ReactAction
  | EditMessageAction
  | DispatchSubagentAction
  | EnqueueMainAction;

export interface OutboundDispatchResult {
  action: BrainOutboundAction;
  status: "queued" | "sent" | "stored" | "skipped" | "failed";
  externalMessageId?: string;
  error?: string;
}

export function originatingTarget(event: EntryPointInboundEvent): OutboundTarget {
  return {
    route: "originating-entrypoint",
    entrypointId: event.entrypoint.entrypointId,
    conversationId: event.conversation?.id,
    threadId: event.conversation?.threadId,
    replyToExternalMessageId: event.kind === "message" ? event.conversation?.metadata?.messageId?.toString() : undefined,
  };
}

export function routeOutboundToOrigin(event: EntryPointInboundEvent, action: BrainOutboundAction): BrainOutboundAction {
  return {
    ...action,
    originatingEventId: action.originatingEventId ?? event.id,
    workspaceId: action.workspaceId ?? event.workspaceId,
    target: action.target ?? originatingTarget(event),
  };
}
