export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonRecord = Record<string, JsonValue>;

export type ChannelKind = "telegram" | "web" | "ios" | "cli" | "loop" | "monitor" | "system" | (string & {});

export type InboundEventKind =
  | "message"
  | "command"
  | "attachment"
  | "callback"
  | "lifecycle"
  | "delivery";

export interface EntryPointCapabilities {
  replies?: boolean;
  edits?: boolean;
  artifactUploads?: boolean;
  statusUpdates?: boolean;
  reactions?: boolean;
  attachments?: boolean;
  commands?: boolean;
  [capability: string]: boolean | undefined;
}

export interface EntryPointRef {
  entrypointId: string;
  channelKind: ChannelKind;
  displayName?: string;
  capabilities?: EntryPointCapabilities;
}

export interface ExternalConversationRef {
  id?: string;
  threadId?: string;
  label?: string;
  url?: string;
  metadata?: JsonRecord;
}

export interface ExternalActorRef {
  id?: string;
  username?: string;
  displayName?: string;
  role?: "user" | "admin" | "system" | "service" | (string & {});
  metadata?: JsonRecord;
}

export interface BrainAttachment {
  id?: string;
  kind: "image" | "document" | "voice" | "audio" | "video" | "unknown" | (string & {});
  localPath?: string;
  uri?: string;
  mimeType?: string;
  originalName?: string;
  sizeBytes?: number;
  sha256?: string;
  metadata?: JsonRecord;
}

export interface ReplyContext {
  externalMessageId?: string;
  snippet?: string;
  contentType?: string;
  actor?: ExternalActorRef;
  metadata?: JsonRecord;
}

export interface EntryPointInboundEvent {
  /** Stable event id generated by the adapter/runtime boundary. */
  id: string;
  kind: InboundEventKind;
  workspaceId: string;
  entrypoint: EntryPointRef;
  /** Plain text normalized for provider prompts. */
  text?: string;
  /** Slash-command or adapter command name without channel-specific syntax. */
  command?: string;
  args?: string[];
  attachments?: BrainAttachment[];
  actor?: ExternalActorRef;
  conversation?: ExternalConversationRef;
  reply?: ReplyContext;
  correlationId?: string;
  receivedAt: string;
  metadata?: JsonRecord;
}

export type OutboundRoute = "originating-entrypoint" | "explicit-entrypoint" | "admins" | "store-only" | "silent";

export interface OutboundTarget {
  route?: OutboundRoute;
  entrypointId?: string;
  conversationId?: string;
  threadId?: string;
  replyToExternalMessageId?: string;
}

export interface BaseOutboundAction {
  id?: string;
  idempotencyKey?: string;
  originatingEventId?: string;
  workspaceId?: string;
  target?: OutboundTarget;
  createdAt?: string;
  metadata?: JsonRecord;
}

export interface SendTextAction extends BaseOutboundAction {
  type: "send_text";
  text: string;
  format?: "text" | "markdown" | "markdownv2";
}

export interface SendArtifactAction extends BaseOutboundAction {
  type: "send_artifact";
  path?: string;
  uri?: string;
  caption?: string;
  asDocument?: boolean;
  deleteAfterSend?: boolean;
  mimeType?: string;
}

export interface ShowStatusAction extends BaseOutboundAction {
  type: "show_status";
  status: "typing" | "running" | "done" | "failed" | "cancelled" | (string & {});
  text?: string;
}

export interface RequestClarificationAction extends BaseOutboundAction {
  type: "request_clarification";
  text: string;
  choices?: string[];
}

export interface ReactAction extends BaseOutboundAction {
  type: "react";
  emoji: string;
}

export interface EditMessageAction extends BaseOutboundAction {
  type: "edit_message";
  text: string;
  externalMessageId?: string;
  format?: "text" | "markdown" | "markdownv2";
}

export interface DispatchSubagentAction extends BaseOutboundAction {
  type: "dispatch_subagent";
  profile: string;
  prompt: string;
  summary: string;
  route?: "return_to_main" | "send_to_user" | "send_progress_and_return" | "send_to_admins" | "store_only" | "silent";
  timeoutSec?: number;
  model?: string;
  effort?: "none" | "minimal" | "low" | "medium" | "high" | "xhigh";
  images?: string[];
}

export interface CancelSubagentAction extends BaseOutboundAction {
  type: "cancel_subagent";
  jobId: string;
  reason?: string;
}

export interface SteerSubagentAction extends BaseOutboundAction {
  type: "steer_subagent";
  jobId: string;
  text: string;
}

export interface EnqueueMainAction extends BaseOutboundAction {
  type: "enqueue_main";
  text: string;
}

export type BrainOutboundAction =
  | SendTextAction
  | SendArtifactAction
  | ShowStatusAction
  | RequestClarificationAction
  | ReactAction
  | EditMessageAction
  | DispatchSubagentAction
  | CancelSubagentAction
  | SteerSubagentAction
  | EnqueueMainAction;

export interface OutboundDispatchResult {
  action: BrainOutboundAction;
  status: "queued" | "sent" | "stored" | "skipped" | "failed";
  externalMessageId?: string;
  error?: string;
}

export interface EntryPointHealth {
  ok: boolean;
  entrypointId: string;
  detail?: string;
  lastEventId?: string;
}

export interface BrainEntrypointAdapter {
  readonly id: string;
  readonly ref: EntryPointRef;
  start?(): Promise<void>;
  stop?(): Promise<void>;
  health?(): Promise<EntryPointHealth>;
  inboundEvents(): AsyncIterable<EntryPointInboundEvent>;
  dispatch(action: BrainOutboundAction): Promise<OutboundDispatchResult>;
}

export interface FakeEntrypointOptions {
  workspaceId: string;
  entrypointId?: string;
  channelKind?: ChannelKind;
  displayName?: string;
  capabilities?: EntryPointCapabilities;
  conversationId?: string;
  actor?: ExternalActorRef;
  dispatchStatus?: OutboundDispatchResult["status"];
  now?: () => Date;
}

export interface FakeInboundTextOptions {
  id?: string;
  kind?: InboundEventKind;
  command?: string;
  args?: string[];
  attachments?: BrainAttachment[];
  conversationId?: string;
  threadId?: string;
  actor?: ExternalActorRef;
  metadata?: JsonRecord;
  correlationId?: string;
  receivedAt?: string;
}

export class FakeEntrypointAdapter implements BrainEntrypointAdapter {
  readonly id: string;
  readonly ref: EntryPointRef;
  readonly dispatchedActions: BrainOutboundAction[] = [];
  readonly dispatchResults: OutboundDispatchResult[] = [];
  private readonly queue: EntryPointInboundEvent[] = [];
  private readonly waiters: Array<(next: IteratorResult<EntryPointInboundEvent>) => void> = [];
  private eventCounter = 0;
  private closed = false;
  private started = false;
  private lastEventId?: string;

  constructor(private readonly options: FakeEntrypointOptions) {
    this.id = options.entrypointId ?? "fake-main";
    this.ref = {
      entrypointId: this.id,
      channelKind: options.channelKind ?? "fake",
      displayName: options.displayName ?? "Fake entrypoint",
      capabilities: options.capabilities ?? {
        replies: true,
        edits: true,
        artifactUploads: true,
        statusUpdates: true,
        reactions: true,
        attachments: true,
        commands: true,
      },
    };
  }

  async start(): Promise<void> {
    this.started = true;
  }

  async stop(): Promise<void> {
    this.started = false;
    this.close();
  }

  async health(): Promise<EntryPointHealth> {
    return {
      ok: this.started && !this.closed,
      entrypointId: this.id,
      detail: this.started ? (this.closed ? "closed" : "started") : "stopped",
      lastEventId: this.lastEventId,
    };
  }

  enqueue(event: EntryPointInboundEvent): EntryPointInboundEvent {
    if (this.closed) throw new Error(`Fake entrypoint ${this.id} is closed`);
    const normalized = { ...event, entrypoint: event.entrypoint ?? this.ref };
    this.lastEventId = normalized.id;
    const waiter = this.waiters.shift();
    if (waiter) waiter({ value: normalized, done: false });
    else this.queue.push(normalized);
    return normalized;
  }

  enqueueText(text: string, options: FakeInboundTextOptions = {}): EntryPointInboundEvent {
    return this.enqueue({
      id: options.id ?? `${this.id}_event_${++this.eventCounter}`,
      kind: options.kind ?? (options.command ? "command" : "message"),
      workspaceId: this.options.workspaceId,
      entrypoint: this.ref,
      text,
      command: options.command,
      args: options.args,
      attachments: options.attachments,
      actor: options.actor ?? this.options.actor,
      conversation: {
        id: options.conversationId ?? this.options.conversationId ?? `${this.id}_conversation`,
        threadId: options.threadId,
      },
      correlationId: options.correlationId,
      receivedAt: options.receivedAt ?? this.nowIso(),
      metadata: options.metadata,
    });
  }

  close(): void {
    if (this.closed) return;
    this.closed = true;
    while (this.waiters.length) {
      const waiter = this.waiters.shift();
      waiter?.({ value: undefined as never, done: true });
    }
  }

  async *inboundEvents(): AsyncIterable<EntryPointInboundEvent> {
    while (true) {
      const next = await this.nextInboundEvent();
      if (next.done) return;
      yield next.value;
    }
  }

  async dispatch(action: BrainOutboundAction): Promise<OutboundDispatchResult> {
    this.dispatchedActions.push(action);
    const result = { action, status: this.options.dispatchStatus ?? "queued" } satisfies OutboundDispatchResult;
    this.dispatchResults.push(result);
    return result;
  }

  private nextInboundEvent(): Promise<IteratorResult<EntryPointInboundEvent>> {
    const queued = this.queue.shift();
    if (queued) return Promise.resolve({ value: queued, done: false });
    if (this.closed) return Promise.resolve({ value: undefined as never, done: true });
    return new Promise((resolve) => this.waiters.push(resolve));
  }

  private nowIso(): string {
    return (this.options.now?.() ?? new Date()).toISOString();
  }
}

export function originatingTarget(event: EntryPointInboundEvent): OutboundTarget {
  return {
    route: "originating-entrypoint",
    entrypointId: event.entrypoint.entrypointId,
    conversationId: event.conversation?.id,
    threadId: event.conversation?.threadId,
    replyToExternalMessageId: event.kind === "message" ? event.conversation?.metadata?.messageId?.toString() : undefined,
  };
}

export function routeOutboundToOrigin(event: EntryPointInboundEvent, action: BrainOutboundAction): BrainOutboundAction {
  const origin = originatingTarget(event);
  return {
    ...action,
    originatingEventId: action.originatingEventId ?? event.id,
    workspaceId: action.workspaceId ?? event.workspaceId,
    target: action.target ? mergeTargetWithOrigin(action.target, origin) : origin,
  };
}

function mergeTargetWithOrigin(target: OutboundTarget, origin: OutboundTarget): OutboundTarget {
  const route = target.route ?? origin.route;
  if (route === "admins" || route === "store-only" || route === "silent") return { ...target, route };
  const useOriginConversation = route === "originating-entrypoint";
  return {
    route,
    entrypointId: target.entrypointId ?? origin.entrypointId,
    conversationId: target.conversationId ?? (useOriginConversation ? origin.conversationId : undefined),
    threadId: target.threadId ?? (useOriginConversation ? origin.threadId : undefined),
    replyToExternalMessageId: target.replyToExternalMessageId ?? (useOriginConversation ? origin.replyToExternalMessageId : undefined),
  };
}
